require 'pgp/packet/sigsubpacket/creationtime'
require 'pgp/packet/sigsubpacket/preferredskeyalgorithm'
require 'pgp/packet/sigsubpacket/primaryuserid'
require 'pgp/packet/sigsubpacket/keyflags'
require 'pgp/packet/sigsubpacket/features'
require 'pgp/packet/sigsubpacket/issuerkeyid'
